---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist

- name: Install dependencies
  apt:
    name: "{{ packages_debian }}"
    state: present
    update_cache: yes

- name: Add an apt signing key for Docker
  apt_key:
    url: "{{ debian_url_key }}"
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: "{{ debian_repo }}"
    state: present

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ debian_docker_name }}"
    group: docker
  notify: Restart docker
 
- include_tasks: web_run_docker.yml
