---
- name: Ensure old versions of Docker are not installed.
  yum:
    name: "{{ docker_packages }}"
    state: absent

- name: Add signing key
  ansible.builtin.rpm_key:
    key: "{{ redhat_url_key }}"
    state: present

- name: Docker repo
  yum_repository:
    name: docker
    description: repo for docker
    baseurl: "{{ redHat_repo }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ redhat_url_key }}"

- name: install liberes
  yum:
    name: "{{ packages_redHat }}"
    state: installed

- name: Install Docker
  yum:
    name: "{{ docker_packages }}"
    state: installed
    update_cache: true

- name: Add user to docker group
  user:
    name: "{{ os_user_redhat }}"
    group: docker

- name: install 'Docker SDK for Python'
  pip:
    name: docker

- name: Restart docker
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
     - containerd.service
     - docker.service

- include_tasks: web_run_docker.yml
